"""
Online snapshot dashboard for the Automated Data Pipeline.

This app is designed for Streamlit Cloud. It does not connect to the local
PostgreSQL instance and does not read local runtime logs. Instead, it reads
published CSV snapshots generated by export_dashboard_snapshots.py.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_DIR = PROJECT_ROOT / "dashboard" / "snapshots"

st.set_page_config(
    page_title="Automated Data Pipeline Demo",
    page_icon="📊",
    layout="wide",
)


@st.cache_data(ttl=300)
def read_snapshot(filename: str) -> pd.DataFrame:
    """Read a dashboard snapshot CSV."""

    path = SNAPSHOT_DIR / filename

    if not path.exists():
        return pd.DataFrame()

    return pd.read_csv(path)


def load_run_summary() -> pd.DataFrame:
    return read_snapshot("pipeline_run_summary.csv")


def load_steps() -> pd.DataFrame:
    return read_snapshot("pipeline_steps.csv")


def load_quality() -> pd.DataFrame:
    return read_snapshot("data_quality_results.csv")


def load_inventory() -> pd.DataFrame:
    return read_snapshot("data_inventory.csv")


def load_market_sample() -> pd.DataFrame:
    return read_snapshot("openbb_market_data_sample.csv")


def load_ohlc_investigation() -> pd.DataFrame:
    return read_snapshot("ohlc_inconsistency_investigation.csv")


def render_sidebar() -> str:
    st.sidebar.title("Pipeline Demo")

    page = st.sidebar.radio(
        "Navigation",
        [
            "Project Overview",
            "Data Quality",
            "Data Inventory",
        ],
    )

    st.sidebar.info(
        "This deployed dashboard uses published snapshots from the latest "
        "successful local pipeline run."
    )

    return page


def render_overview() -> None:
    st.title("Automated Data Pipeline")
    st.caption(
        "Online portfolio snapshot of the OpenBB, FRED, Sina Finance, "
        "PostgreSQL, and data-quality workflow."
    )

    summary = load_run_summary()
    steps = load_steps()
    inventory = load_inventory()
    quality = load_quality()

    if summary.empty:
        st.warning(
            "Pipeline summary snapshot is unavailable. "
            "Run export_dashboard_snapshots.py locally."
        )
        return

    row = summary.iloc[0]

    warning_count = 0
    failure_count = 0

    if not quality.empty and "check_result" in quality.columns:
        warning_count = int((quality["check_result"] == "WARNING").sum())
        failure_count = int((quality["check_result"] == "FAIL").sum())

    col1, col2, col3, col4 = st.columns(4)

    col1.metric(
        "Latest Published Run",
        str(row.get("status", "UNKNOWN")),
    )

    runtime = row.get("runtime_seconds")
    col2.metric(
        "Runtime",
        f"{float(runtime):.2f} sec" if pd.notna(runtime) else "N/A",
    )

    col3.metric("Warnings", warning_count)
    col4.metric("Failures", failure_count)

    st.subheader("Published Data Snapshot")

    if not inventory.empty:
        st.dataframe(
            inventory,
            width='stretch',
            hide_index=True,
        )

    st.subheader("Pipeline Workflow")

    if steps.empty:
        st.info("No pipeline-step snapshot is available.")
    else:
        preferred = [
            "step_number",
            "step_name",
            "status",
            "runtime_seconds",
        ]

        visible = [
            column for column in preferred
            if column in steps.columns
        ]

        st.dataframe(
            steps[visible],
            width='stretch',
            hide_index=True,
        )

        if "status" in steps.columns:
            completed = int((steps["status"] == "PASS").sum())
            total = len(steps)

            if total:
                st.progress(
                    min(completed / total, 1.0),
                    text=f"{completed} of {total} steps completed",
                )

    st.info(
        "The production-style local version reads PostgreSQL and runtime logs. "
        "This online version is a read-only portfolio demonstration."
    )


def render_quality() -> None:
    st.title("Data Quality Snapshot")
    st.caption(
        "Latest published validation results from the local ETL pipeline."
    )

    quality = load_quality()

    if quality.empty:
        st.warning("No data-quality snapshot is available.")
        return

    counts = (
        quality["check_result"]
        .value_counts()
        .reindex(["PASS", "WARNING", "FAIL"], fill_value=0)
    )

    col1, col2, col3 = st.columns(3)
    col1.metric("PASS", int(counts["PASS"]))
    col2.metric("WARNING", int(counts["WARNING"]))
    col3.metric("FAIL", int(counts["FAIL"]))

    preferred = [
        "table_name",
        "check_name",
        "check_result",
        "failed_rows",
        "details",
        "check_time",
    ]

    visible = [
        column for column in preferred
        if column in quality.columns
    ]

    st.dataframe(
        quality[visible],
        width='stretch',
        hide_index=True,
    )

    chart_df = (
        quality["check_result"]
        .value_counts()
        .rename_axis("status")
        .reset_index(name="checks")
    )

    fig = px.bar(
        chart_df,
        x="status",
        y="checks",
        text="checks",
        title="Quality Check Status Distribution",
    )

    st.plotly_chart(fig, width='stretch')

    st.subheader("OHLC Investigation")

    ohlc = load_ohlc_investigation()

    if ohlc.empty:
        st.success("No published OHLC investigation rows.")
    else:
        st.warning(
            f"{len(ohlc)} upstream OHLC inconsistencies were retained "
            "for transparent review."
        )

        st.dataframe(
            ohlc,
            width='stretch',
            hide_index=True,
        )


def render_inventory() -> None:
    st.title("Data Inventory and Market Preview")
    st.caption(
        "Published database inventory and a sample of processed OpenBB data."
    )

    inventory = load_inventory()

    if inventory.empty:
        st.warning("No inventory snapshot is available.")
        return

    st.dataframe(
        inventory,
        width='stretch',
        hide_index=True,
    )

    if "dataset" in inventory.columns and "rows" in inventory.columns:
        fig = px.bar(
            inventory,
            x="dataset",
            y="rows",
            text="rows",
            title="Rows by Dataset",
        )

        st.plotly_chart(fig, width='stretch')

    market = load_market_sample()

    if market.empty:
        st.info("No OpenBB market sample is available.")
        return

    required = {"symbol", "asset_name", "date", "close"}

    if not required.issubset(market.columns):
        st.warning(
            "The OpenBB snapshot does not contain the expected columns."
        )
        return

    market["date"] = pd.to_datetime(
        market["date"],
        errors="coerce",
    )

    symbols = (
        market[["symbol", "asset_name"]]
        .drop_duplicates()
        .sort_values("symbol")
    )

    label_map = {
        row["symbol"]: f"{row['symbol']} — {row['asset_name']}"
        for _, row in symbols.iterrows()
    }

    selected = st.selectbox(
        "Select a market series",
        options=symbols["symbol"].tolist(),
        format_func=lambda symbol: label_map[symbol],
    )

    selected_df = (
        market[market["symbol"] == selected]
        .sort_values("date")
    )

    fig = px.line(
        selected_df,
        x="date",
        y="close",
        title=label_map[selected],
    )

    st.plotly_chart(fig, width='stretch')

    col1, col2, col3 = st.columns(3)
    col1.metric("Published Observations", len(selected_df))
    col2.metric(
        "Latest Close",
        f"{selected_df['close'].iloc[-1]:,.4f}",
    )
    col3.metric(
        "Latest Date",
        str(selected_df["date"].max().date()),
    )

    st.dataframe(
        selected_df.tail(20),
        width='stretch',
        hide_index=True,
    )


def main() -> None:
    page = render_sidebar()

    if page == "Project Overview":
        render_overview()
    elif page == "Data Quality":
        render_quality()
    else:
        render_inventory()


if __name__ == "__main__":
    main()
